/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ComponentNameHere {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLComponentNameHereElement extends Components.ComponentNameHere, HTMLStencilElement {}
  var HTMLComponentNameHereElement: {
    prototype: HTMLComponentNameHereElement;
    new (): HTMLComponentNameHereElement;
  };
  interface HTMLElementTagNameMap {
    'component-name-here': HTMLComponentNameHereElement;
  }
}

declare namespace LocalJSX {
  interface ComponentNameHere {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'component-name-here': ComponentNameHere;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'component-name-here': LocalJSX.ComponentNameHere & JSXBase.HTMLAttributes<HTMLComponentNameHereElement>;
    }
  }
}


